# action.yml
name: 'Provenance Smart Contract Test'
description: 'Action to test smart contracts on Provenance'
inputs:
  provenance_version:  # version of Provenance
    description: 'Version of Provenance to test against'
    required: true
    default: 'v1.8.0'
  test_script:
    description: 'Script used to test smart contract after provenance has been setup and run'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test_script }}
    - ${{ inputs.provenance_version }}